image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - chmod +x gradlew
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar artifacts/app-ibank.jar -P:profile=test" -PassThru

build_script:
  - ./gradlew test --info "-Dselenide.headless=true"  # запускаем тест, флаг --info позволяет выводить больше информации
